### ISSUE TITLE
`IsADirectoryError: [Errno 21] Is a directory: '/home/aleksandrk/Desktop/why/layers/'` in `readJson()`

### ISSUE THREAD

**Issue by AlastorTh** [robinuniverse/Keebie#25]
[output.txt](https://github.com/robinuniverse/Keebie/files/6830070/output.txt)

**Comment by ghost** [comment]
Do you mind showing your config file ?

**Comment by Michael-E-B** [comment]
```
python keebie.py
Welcome to Keebie
Traceback (most recent call last):
  File "/home/aleksandrk/Desktop/why/keebie.py", line 736, in <module>
    if "leds" in readJson(config()[1]):
  File "/home/aleksandrk/Desktop/why/keebie.py", line 185, in readJson
    with open(dir+filename) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/aleksandrk/Desktop/why/layers/'
Exception ignored in: <function InputDevice.__del__ at 0x7f4a81e43c10>
Traceback (most recent call last):
  File "/home/aleksandrk/.local/lib/python3.9/site-packages/evdev/device.py", line 160, in __del__
  File "/home/aleksandrk/.local/lib/python3.9/site-packages/evdev/device.py", line 305, in close
  File "/home/aleksandrk/.local/lib/python3.9/site-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.9/asyncio/events.py", line 725, in get_event_loop_policy
  File "/usr/lib/python3.9/asyncio/events.py", line 718, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```

The important section here is
```
Traceback (most recent call last):
  File "/home/aleksandrk/Desktop/why/keebie.py", line 736, in <module>
    if "leds" in readJson(config()[1]):
  File "/home/aleksandrk/Desktop/why/keebie.py", line 185, in readJson
    with open(dir+filename) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/aleksandrk/Desktop/why/layers/'
```

Based on this it appears `keebie.py` is trying to open the layer file specified on line 2 of your `config`, however it seems there is no text on line 2 of `config` and as such it tries to open the directory as a file and crashes. Please ensure that line 2 of `config` contains the filename of a json file in your `layers/` directory.

Also `keebie.py` has a shebang to ensure that it runs under `/usr/bin/env python3` so you should just run it with `$ ./keebie.py` without specifying an interpreter.

**Comment by AlastorTh** [comment]
> Do you mind showing your config file ?

/dev/input/by-id/usb-04f3_0103-event-kbd
default.json

**Comment by Michael-E-B** [comment]
> /dev/input/by-id/usb-04f3_0103-event-kbd
> default.json

Two things here are odd, first unless there is a blank line between the two you showed this code should work. Second unless you omitted the third line of `config` the file is missing it's settings reference (but that shouldn't have an effect until latter lines).

I assume you are running from commit 15a165d5, I'm going to get a copy of that commit and try this.

**Comment by Michael-E-B** [comment]
```
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:33]: ~/Desktop/why
 $ tree
.
├── Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
│   ├── config
│   ├── keebie.py
│   ├── layers
│   │   └── default.json
│   ├── readme.md
│   ├── settings.json
│   └── setup_tools
│       ├── keebie.service
│       └── udevRule.sh
└── Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0.zip

3 directories, 8 files
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:33]: ~/Desktop/why
 $ cd ./Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0/
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:34]: ~/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
 $ nano config
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:34]: ~/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
 $ cat config
/dev/input/event2
default.json
settings.json
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:34]: ~/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
 $ ./keebie.py 
Welcome to Keebie
Loading settings from settings.json
^C
```

When I deliberately made line 2 of `config` blank I was able to reproduce the error:

```
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:41]: ~/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
 $ ./keebie.py 
Welcome to Keebie
Traceback (most recent call last):
  File "./keebie.py", line 735, in <module>
    if "leds" in readJson(config()[1]):
  File "./keebie.py", line 184, in readJson
    with open(dir+filename) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/michael/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0/layers/'
Exception ignored in: <function InputDevice.__del__ at 0x7f39f3b94790>
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.8/site-packages/evdev/device.py", line 159, in __del__
  File "/home/michael/.local/lib/python3.8/site-packages/evdev/device.py", line 304, in close
  File "/home/michael/.local/lib/python3.8/site-packages/evdev/eventio_async.py", line 54, in close
  File "/usr/lib/python3.8/asyncio/events.py", line 722, in get_event_loop_policy
  File "/usr/lib/python3.8/asyncio/events.py", line 715, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
michael-ubuntu-desktop1[michael@] [Mon Jul 19/13:41]: ~/Desktop/why/Keebie-15a165d5f1c4941b670d56ff66473fb601e72bb0
 $ 
```

I noted that the lines I get the error on are one line earlier but have the same contents, this suggests there is an extra line in your copy of `keebie.py` or that I was wrong about what commit you are running from.

**Comment by Michael-E-B** [comment]
Given the lack of reply (as well as the fact the version being run is very out of date and `config` no longer exists) I'm going to close this.
