### ISSUE TITLE
Layers error 

### ISSUE THREAD

**Issue by parasbhanot** [robinuniverse/Keebie#7]
i am getting the following error when i use layers options :

```
Keebie  🌵 master ✈️  ×2 via 🐍 v3.9.1 ❯  ./keebie.py --layers                                                      12:09:00
Welcome to Keebie
Available Layers: 

default.json{
   "KEY_SPACE": "echo 'Hello World!'",
   "KEY_A": "brave"
}

Exception ignored in: <function InputDevice.__del__ at 0x7f3cd1dd5940>
Traceback (most recent call last):
  File "/home/parasbhanot/.local/lib/python3.9/site-packages/evdev/device.py", line 159, in __del__
  File "/home/parasbhanot/.local/lib/python3.9/site-packages/evdev/device.py", line 304, in close
  File "/home/parasbhanot/.local/lib/python3.9/site-packages/evdev/eventio_async.py", line 54, in close
  File "/usr/lib/python3.9/asyncio/events.py", line 725, in get_event_loop_policy
  File "/usr/lib/python3.9/asyncio/events.py", line 718, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```
i am testing this on arch machine with python 3.9.1. 

Any ideas what is causing this import error ?

**Comment by Michael-E-B** [comment]
While this may seem like an error, and it is definitely weird and I don't know why it happens, a very similar message has always been printed on my machine (with python 3.8.5) whenever Keebie exits and has never seemed to indicate an actual problem.

If the same is true of everyone else then I would call this an odd but normal behavior.

**Comment by Michael-E-B** [comment]
For comparison I get :

```
Exception ignored in: <function InputDevice.__del__ at 0x7f02171e0af0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
  File "/usr/lib/python3.8/asyncio/events.py", line 722, in get_event_loop_policy
  File "/usr/lib/python3.8/asyncio/events.py", line 715, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by parasbhanot** [comment]
okhay thanks , 
I will ignore this error for now
